package com.isr.finalisrlogin.entity;
// Generated Dec 1, 2017 11:36:38 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLoginDetail generated by hbm2java
 */
@Entity
@Table(name = "user_login_detail",
         catalog = "isr_project"
)
public class UserLoginDetail implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idUser_login_detail", unique = true, nullable = false)
    private Integer idUserLoginDetail;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "User_idUser", nullable = false)
    private User user;
    @Column(name = "ipaddress", length = 45)
    private String ipaddress;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "intime", length = 19)
    private Date intime;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "outtime", length = 19)
    private Date outtime;
    @Column(name = "browserdetails", length = 45)
    private String browserdetails;
    @Column(name = "operatingsystem", length = 45)
    private String operatingsystem;

    public UserLoginDetail() {
    }

    public UserLoginDetail(User user) {
        this.user = user;
    }

    public UserLoginDetail(User user, String ipaddress, Date intime, Date outtime, String browserdetails, String operatingsystem) {
        this.user = user;
        this.ipaddress = ipaddress;
        this.intime = intime;
        this.outtime = outtime;
        this.browserdetails = browserdetails;
        this.operatingsystem = operatingsystem;
    }

    public Integer getIdUserLoginDetail() {
        return this.idUserLoginDetail;
    }

    public void setIdUserLoginDetail(Integer idUserLoginDetail) {
        this.idUserLoginDetail = idUserLoginDetail;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getIpaddress() {
        return this.ipaddress;
    }

    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    public Date getIntime() {
        return this.intime;
    }

    public void setIntime(Date intime) {
        this.intime = intime;
    }

    public Date getOuttime() {
        return this.outtime;
    }

    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }

    public String getBrowserdetails() {
        return this.browserdetails;
    }

    public void setBrowserdetails(String browserdetails) {
        this.browserdetails = browserdetails;
    }

    public String getOperatingsystem() {
        return this.operatingsystem;
    }

    public void setOperatingsystem(String operatingsystem) {
        this.operatingsystem = operatingsystem;
    }

}
