package com.isr.finalisrlogin.entity;
// Generated Dec 1, 2017 11:36:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by Bhagya
 */
@Entity
@Table(name = "user",
         catalog = "isr_project"
)
public class User implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idUser", unique = true, nullable = false)
    private Integer idUser;
    @Column(name = "fname", length = 45)
    private String fname;
    @Column(name = "lname", length = 45)
    private String lname;
    @Column(name = "email", length = 45)
    private String email;
    @Column(name = "Mobile", length = 15)
    private String mobile;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    private Set<UserLoginDetail> userLoginDetails = new HashSet(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    private Set<UserLogin> userLogins = new HashSet(0);

    public User() {
    }

    public User(String fname, String lname, String email, String mobile, Set userLoginDetails, Set userLogins) {
        this.fname = fname;
        this.lname = lname;
        this.email = email;
        this.mobile = mobile;
        this.userLoginDetails = userLoginDetails;
        this.userLogins = userLogins;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    public Set getUserLoginDetails() {
        return this.userLoginDetails;
    }

    public void setUserLoginDetails(Set<UserLoginDetail> userLoginDetails) {
        this.userLoginDetails = userLoginDetails;
    }

    public Set getUserLogins() {
        return this.userLogins;
    }

    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }

}
