package com.isr.finalisrlogin.entity;
// Generated Dec 1, 2017 11:36:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "user_type", catalog = "isr_project")
public class UserType implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idUser_type", unique = true, nullable = false)
    private Integer idUserType;
    @Column(name = "name", length = 45)
    private String name;
    @Column(name = "status")
    private Integer status;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userType")
    private Set<UserLogin> userLogins = new HashSet(0);

    public UserType() {
    }

    public UserType(String name, Integer status, Set userLogins) {
        this.name = name;
        this.status = status;
        this.userLogins = userLogins;
    }

    public Integer getIdUserType() {
        return this.idUserType;
    }

    public void setIdUserType(Integer idUserType) {
        this.idUserType = idUserType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Set getUserLogins() {
        return this.userLogins;
    }

    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }

}
