package com.isr.finalisrlogin.entity;
// Generated Dec 1, 2017 11:36:38 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name = "user_login",
         catalog = "isr_project"
)
public class UserLogin implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idUser_login", unique = true, nullable = false)
    private Integer idUserLogin;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "User_idUser", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "User_type_idUser_type", nullable = false)
    private UserType userType;
    @Column(name = "username", length = 45)
    private String username;
    @Column(name = "password", length = 45)
    private String password;
    @Column(name = "Status")
    private Integer status;

    public UserLogin() {
    }

    public UserLogin(User user, UserType userType) {
        this.user = user;
        this.userType = userType;
    }

    public UserLogin(User user, UserType userType, String username, String password, Integer status) {
        this.user = user;
        this.userType = userType;
        this.username = username;
        this.password = password;
        this.status = status;
    }

    public Integer getIdUserLogin() {
        return this.idUserLogin;
    }

    public void setIdUserLogin(Integer idUserLogin) {
        this.idUserLogin = idUserLogin;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
